apiVersion: v1
kind: Service
metadata:
  name: community-service
spec:
  type: ClusterIP
  selector:
    app: community-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-deployment
  namespace: default
  labels:
    app: community
spec:
  replicas: 3
  selector:
    matchLabels:
      app: community 
      
#  strategy:
#    rollingUpdate:
#      maxSurge: 1
#      maxUnavailable: 1
#    type: RollingUpdate
  template:
    metadata:
      labels:
        app: community
    spec:
      containers:
        - name: community
#          image: 518370512832.dkr.ecr.ap-northeast-2.amazonaws.com/community-template:dev-38
          image: AWS_ECR_URI
          ports:
            - containerPort: 80
          imagePullPolicy: Always
#          resources:
#            requests:
#              cpu: "256m"
#              memory: "512Mi"
#            limits:
#              cpu: "256m"
#              memory: "512Mi"
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: "backend-ingress"
#  namespace: default
#  annotations:
#    kubernetes.io/ingress.class: alb
#    alb.ingress.kubernetes.io/scheme: internal
#    alb.ingress.kubernetes.io/target-type: ip
#spec:
#  rules:
#  - http:
#      paths:
#        - path: /
#          pathType: Prefix
#          backend:
#            service:
#              name: "community-service"
#              port:
#                number: 80         